feat: add quiz event
he4rt/he4rt-bot-next pull request #83
Opened 2023-04-23 13:34 UTC by fernanduandrade

@Novout PR draft do evento de coding para o bot

2023-05-21 15:28 UTC, Novout commented
Agora com o firebase acho que dá para implementar isso. Teria como resolver os conflitos @fernanduandrade ?

2023-05-24 09:32 UTC, fernanduandrade commented
Salve @Novout, pode deixar consigo sim

2023-06-06 00:54 UTC, fernanduandrade commented
@Novout @kjkGustavo resolvi os conflitos, a principio a lógica tá feita, mas tem muito a ser refinado ainda
- Adicionei um cron job para fazer o evento ficar disponível baseado na data de inicio e disparar uma mensagem no canal
- Validação para quando não tiver um evento ativo e ser usado o comando
- Validação para quando um usuário completar o evento

Exemplo do fluxo no chat:
![Screenshot from 2023-06-05 21-40-30](https://github.com/he4rt/he4rt-bot-next/assets/58053397/05be0ebd-66af-48b2-9b87-af1197abd3ce)

Exemplo do fluxo na DM:
![Screenshot from 2023-06-05 21-41-12](https://github.com/he4rt/he4rt-bot-next/assets/58053397/d773da8b-76eb-4424-8e5e-0762612750a6)

2023-06-16 00:21 UTC, Novout requested changes

2023-06-16 00:21 UTC, Novout commented on src/commands/quiz_event.ts
> +      color: '#FF0000'
Acho que as cores poderiam estar em `src/defines/values.json -> COLORS`

2023-06-16 00:21 UTC, Novout commented on src/http/firebase.ts
> +  collection.doc(reward.id).set(entity)
Retorno da promise

```suggestion
  collection.doc(reward.id).set(entity)
  return collection.doc(reward.id).set(entity)
```

2023-06-16 00:21 UTC, Novout commented on src/http/firebase.ts
> +  collection.doc(event.id).set(entity)
Retorno da promise

```suggestion
  collection.doc(event.id).set(entity)
  return collection.doc(reward.id).set(entity)
```

2023-06-16 00:22 UTC, Novout commented
@fernanduandrade a branch develop foi removida, mas se quiser eu crio aqui sem problemas.

2023-07-03 00:03 UTC, fernanduandrade commented
@Novout  boa noite, modificações realizadas 👍

2023-08-01 10:49 UTC, Novout commented
@fernanduandrade está funcional ao ponto de ser aprovado?

2023-08-01 22:24 UTC, fernanduandrade commented
> @fernanduandrade está funcional ao ponto de ser aprovado?

boa noite, o fluxo do quiz sim, entretanto o fluxo de dar o exp e coins do usuário não. Essa parte n compreendi muito bem vendo as chamadas da api.

2023-11-29 11:51 UTC, Canhassi12 commented on src/commands/quiz_event.ts
> +
Faz sentido usarmos um try catch se não estamos usando? Qual erro poderia dar nesse trecho? 

Se for algo não possivel de se tratar, ok. Mas caso contrario pode deixar, apenas renomeie a variavel `e` para `exception` por mais que não use é importante dar nomes declararitivos.

2023-11-29 11:51 UTC, Canhassi12 commented on src/commands/quiz_event.ts
> +    }
else if? else???????????????

2023-11-29 11:51 UTC, Canhassi12 commented on src/commands/quiz_event.ts
> +    }
Faz 4 if @fernanduandrade que é melhor kkkkkkkk

Ou abre uma PR para o JS e faz um pattern match, ia ser bom

2023-11-29 11:51 UTC, Canhassi12 commented on src/events/cron/quiz.ts
> +      if(event.is_active && event.date_end.toDate() < today) {
```suggestion
      if (event.is_active && event.date_end.toDate() < today) {
```

2023-11-29 11:51 UTC, Canhassi12 commented on src/events/cron/quiz.ts
tem código repetido que poderia ser criado uma variável para não repeti-los.

> event.date_end.toDate()

2023-11-29 11:51 UTC, Canhassi12 commented on src/http/firebase.ts
> +        .get()
não sei que ORM é esse, mas quando é uma query que verifica se é `=` voce precisa escreve `'='` ?


no Eloquent do laravel podemos fazer assim:  where('fk_event', eventId). Enfim wathever

2023-11-29 11:51 UTC, Canhassi12 commented on src/http/firebase.ts
> +}
```suggestion
}

```

2023-11-29 11:51 UTC, Canhassi12 commented on src/types.ts
> +}
```suggestion
}

```

2023-11-29 13:58 UTC, SamucaDev commented on src/commands/index.ts
> +    // useReputation()
remove?

2023-11-29 13:58 UTC, SamucaDev commented on src/commands/index.ts
> +  for (const [key, cb] of client.commands) {
Talvez nomes mais sugestivos para substituir Key e CB

2023-11-29 13:58 UTC, SamucaDev commented on src/commands/quiz_event.ts
> +  const value = Number(await nextTextMessage(dm, interaction))
O que é este Value?

2023-11-29 13:58 UTC, SamucaDev commented on src/events/discord/channel.ts
> +      // provider_message_parent_id: message.parentId
```suggestion
```

2023-11-29 15:36 UTC, fernanduandrade commented on src/http/firebase.ts
> +        .get()
O segundo param obrigatorio do método where do firebaseStore é o tipo de filtro da consulta, `'=='`
![image](https://github.com/he4rt/he4rt-bot-next/assets/58053397/280ffca1-5b6a-47a7-9c88-e4909763b624)

2023-11-29 15:41 UTC, fernanduandrade commented on src/events/cron/quiz.ts
A nomeclatura a mesma mais não pode criar um variável pois são 2 operações de iterações diferentes

2025-12-04 11:46 UTC, closed without merging