feat: new crystal role
he4rt/he4rt-bot-next pull request #86
Opened 2023-07-24 04:25 UTC by lanjoni

# Adicionando cargo para Crystal

Adicionando cargo com nome `Crystal 🖤` para desenvolvedores entusiastas no desenvolvimento com a linguagem de programação Crystal.

2023-07-24 04:28 UTC, J0sueTM approved these changes

2023-07-24 04:41 UTC, yayaflc commented
LGTM

2023-07-25 01:46 UTC, DanielHe4rt approved these changes

2023-07-25 01:46 UTC, DanielHe4rt commented
@Novout quando quiser.

2023-07-25 01:49 UTC, fernanduandrade approved these changes
Looks good to me

2023-08-01 10:51 UTC, Novout requested changes

2023-08-01 10:51 UTC, Novout commented on src/defines/ids.json
> +      "id": "id",
Falta inserir o id do cargo, alguém tem que criar o cargo e mudar o id aqui.

2023-08-01 10:51 UTC, Novout commented on src/defines/ids_development.json
> +      "id": "id",
Falta inserir o id do cargo, alguém tem que criar o cargo e mudar o id aqui.

2023-08-02 18:49 UTC, DanielHe4rt commented on src/defines/ids_development.json
> +      "id": "id",
ID criado: 1136369892736647359

2023-08-02 18:49 UTC, DanielHe4rt commented on src/defines/ids.json
> +      "id": "id",
Id criado: 1136369892736647359
cc: @lanjoni @Novout

2023-08-02 19:26 UTC, Ujs74wiop6 commented
LGTM

2023-08-02 23:10 UTC, jpaulohe4rt approved these changes

2023-08-03 13:25 UTC, merged